### ISSUE TITLE
OEM deals - tracking in SF

### ISSUE THREAD

**Issue by ruipperez** [CartoDB/RevOps#364]
Ensure the right tracking of OEM deals.

- [x] Add OEM to Primary Usage Model - DONE

- [x] Rename OEM Products:

OEM - Cloud - License - done
OEM - On-Premises / Self-hosted - License - done
OEM - Additional Users - PENDING 

EXC - OEM - Usage-Based Fee - make obsolete (waiting for Juliana's open renewal)

- [x] Troops signals to be fired at a new channel **#legal-signals**:

Criteria: If Primary Usage Model = OEM OR Commercial Application OR Opp Name contains OEM - @JuanKTrejo working on this

- [x] Draft email to team presenting common scenarios for OEM:
1. Different pricing - special terms
2. If the client will grant access to CARTO Platform to third parties
3. If the client will develop an app which includes CARTO

Notes

- It was agreed to not differentiate OEM types (Partnership vs End Customer) in SF for now.
